swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
#    port: "%mailer_port%"
    username: "%mailer_user%"
    password: "%mailer_password%"
#    encryption: "%mailer_encryption%"
#    auth_mode: "%mailer_auth_mode%"
    spool: { type: memory }
    disable_delivery: "%mailer_disable_delivery%"
    delivery_addresses: ["%mailer_master_email_address%"]
    delivery_whitelist: "%mailer_delivery_whitelist%"
