parameters:
  database_driver: pdo_pgsql
  database_server_version: 12.1
  # Symfony's FrameworkBundle sets throw_at (error_reporting) to 0 in production by default
  debug.error_handler.throw_at: -1
  locale: en
  # Performance test parameters
  newsandmedia.performance_data.category.counts_by_level: [2, 4, 6]
  newsandmedia.performance_data.product.total_count: 40000
  newsandmedia.performance_data.user.count_per_domain: 100
  newsandmedia.performance_data.order.total_count: 50000
  newsandmedia.performance_data.order.item_count_per_order: 6
  newsandmedia.performance_test.page.duration_milliseconds.warning: 1000
  newsandmedia.performance_test.page.duration_milliseconds.critical: 3000
  newsandmedia.performance_test.page.query_count.warning: 100
  newsandmedia.performance_test.page.query_count.critical: 300
  newsandmedia.performance_test.feed.max_duration_seconds: 180
  newsandmedia.performance_test.feed.delivery.max_duration_seconds: 20
  newsandmedia.performance_test.feed.min_duration_seconds: 5
  container.autowiring.strict_mode: true
  container.dumper.inline_class_loader: true
  build-version: '0000000000000000_%kernel.environment%'
  newsandmedia.display_timezone: Europe/Bratislava
  newsandmedia.cron_timezone: Europe/Bratislava
  newsandmedia.image.enable_lazy_load: false
  # Default extended classes mapping
  newsandmedia.entity_extension.map: { }
  newsandmedia.display_cron_overview_for_superadmin_only: true
  env(IGNORE_DEFAULT_ADMIN_PASSWORD_CHECK): '1'
  env(REDIS_PREFIX): ''
  env(ELASTIC_SEARCH_INDEX_PREFIX): ''
